name: Deploy Application

on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    runs-on: ubuntu-latest # Ini akan menggunakan versi Node terbaru yang disokong secara automatik

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Gunakan v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Gunakan LTS versi 22 atau '24' untuk mengelakkan amaran deprecation

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Gunakan v4
        with:
          name: build-output
          path: .
